Scala play starter
qqupp/scalastuff pull request #1
Opened 2017-08-10 19:02 UTC by qqupp

2017-08-10 21:59 UTC, SilverPhoenix99 requested changes

2017-08-10 21:59 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +      Ok(views.txt.text("Nothing to see here!"))
Can you change this from `Ok` to `NotFound`, please? It will show the same in the browser, but the status will be 404 instead of 200.

2017-08-10 21:59 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +    val rndString = EightBallReply.getRndBall.content
Rename to `randomMessage` and `getRandomBall`.

2017-08-10 21:59 UTC, SilverPhoenix99 commented on app/views/text.scala.txt
> +@(text: String)
I get what you were trying to do here, but you can pass strings directly in the `Ok` (or similar) method.
You can delete this file.

2017-08-10 21:59 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +    Ok(views.txt.text(rndString))
You can replace the parameter of all of these calls to `Ok` with passing the string directly.

2017-08-10 22:06 UTC, qqupp commented on app/controllers/EightBallController.scala
> +    val rndString = EightBallReply.getRndBall.content
while randomMessage it's more uniform and I can see why, I don't see the reason behind getRandomBall vs getRndBall

2017-08-10 22:08 UTC, qqupp commented on app/controllers/EightBallController.scala
> +      fold("")((x:String, y:String) => x + "\n" + y)
just a matter of stile, but for sure is more concise a 
fold("")( _ + "\n" + _ )

any thought?

2017-08-10 22:18 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +      fold("")((x:String, y:String) => x + "\n" + y)
I'd acxept it for the `map`. You can use `mkString("\n")` if I'm not mistaken.

2017-08-10 22:20 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +    val rndString = EightBallReply.getRndBall.content
Just for consistency in the naming.

2017-08-10 22:21 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +  def getMessages = Action {
Can you change this to `messages`, please? The way it is now is more Java than Scala.

2017-08-10 22:27 UTC, SilverPhoenix99 requested changes

2017-08-10 22:27 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +  def getMessage(id: Int) = Action {
Change to `message`, please.

2017-08-10 22:27 UTC, SilverPhoenix99 commented on conf/routes
> +GET     /eight-ball                         controllers.EightBallController.randomReply
If this is the "root" of the controller, the method should be called `index`.

2017-08-11 06:51 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +  def getMessages = Action {
Hold on this one.

2017-08-11 06:51 UTC, SilverPhoenix99 commented on app/controllers/EightBallController.scala
> +  def getMessage(id: Int) = Action {
Hold on this one too.

2017-08-11 13:38 UTC, qqupp commented on app/controllers/EightBallController.scala
> +      fold("")((x:String, y:String) => x + "\n" + y)
Just for ref  https://docs.scala-lang.org/style/declarations.html
"Function Values" section

2017-08-11 17:36 UTC, qqupp commented on app/controllers/EightBallController.scala
> +    val rndString = EightBallReply.getRndBall.content
Fixed

2017-08-16 17:02 UTC, SilverPhoenix99 commented on conf/routes
> +GET     /eight-ball                         controllers.EightBallController.randomReply
As discussed before, we'll keep this as is.

2017-08-16 17:02 UTC, SilverPhoenix99 approved these changes

2017-08-16 17:03 UTC, merged